### ISSUE TITLE
Debug messages in e-Internationalization

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#10]
e-Internationalization creates a lot of debug messages. They do not use a logger but are printed directly to the console. Usually I dont complain about a few lines printed directly to the console but in e-Internationalization it is too much. It prints douzens / hundred of lines on the console so I get lost while working on the code.

Please print these information using a log4j logger and use log level debug. Then everyone can switch on / off this information via configuration.

You can copy the log4j.properties from the broker.

**Comment by borriellom** [comment]
Sorry, I totally agree with you. Those messages were for my testing purpose. Usually I remove all of  them, but this time I forgot. I'm going to delete them

**Comment by borriellom** [comment]
Debug messages deleted

**Comment by jnehring** [comment]
Thanks
