### ISSUE TITLE
[test] HTML is extended with unnecessary elements

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#12]
When submitting following request

    curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d "<p>Welcome to Berlin, the capital of Germany.</p>" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all" -v

where the input is:

    <p>Welcome to Berlin, the capital of Germany.</p>

... the result is:

    <html><head><body><p>Welcome to <span its-ta-ident-ref="http://dbpedia.org/resource/Berlin">Berlin</span>, the capital of <span its-ta-ident-ref="http://dbpedia.org/resource/Germany">Germany</span>.</p></body></html>

Note that the the HTML is extended with unnecessary elements such as `<html>`, `<head><body>` - These elements were not present in the input and IMO they should not also occur in the output.

**Comment by borriellom** [comment]
This is a behavior generated by Okapi. See issue #7

**Comment by m1ci** [comment]
oh, yes, closing this issue since it is already documented in https://github.com/freme-project/e-Internationalization/issues/8
