### ISSUE TITLE
[test] incorrect error message

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#13]
For 

    curl -X POST --header "Content-Type: text/turtle" --header "Accept: text/html" -d @test-e-link.txt "http://api-dev.freme-project.eu/current/e-link/documents?templateid=1" -v

and the data: [test-e-link.txt](https://github.com/freme-project/e-Internationalization/files/19299/test-e-link.txt)

...the results is:
```
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Oct 23 13:20:36 CEST 2015</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Can only convert to outformat &quot;text/html&quot; when informat is also &quot;text/html&quot;</div></body></html>
```

The error should be formated same as the errors of the other services - as JSON.

**Comment by jnehring** [comment]
The error originates from the broker. I will take care for it.

**Comment by jnehring** [comment]
Solved. Please check and close if the error is solved.

**Comment by m1ci** [comment]
works.
