### ISSUE TITLE
[test] not clear what combinations of input/output formats are valid

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#14]
I send turtle to e-Link and request the results in HTML. I'm not sure if this combination is considered but if not, then this should be clearly stated in the documentation.

The request is:

    curl -X POST --header "Content-Type: text/turtle" --header "Accept: text/html" -d @test-e-link.txt "http://api-dev.freme-project.eu/current/e-link/documents?templateid=1" -v

The turtle is: [test-e-link.txt](https://github.com/freme-project/e-Internationalization/files/19299/test-e-link.txt)

The results is:
```
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Oct 23 13:20:36 CEST 2015</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Can only convert to outformat &quot;text/html&quot; when informat is also &quot;text/html&quot;</div></body></html>
```

- 1) its not clear if this combination of input/output format is supported.
- 2) the error should be formated same as the errors of the other services (created separated issue for this https://github.com/freme-project/e-Internationalization/issues/13)

**Comment by jnehring** [comment]
@borriellom please add a line to the [e-internationlization documentation](http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html) that states that roundtripping only works when the input format is equal to the output format.

**Comment by borriellom** [comment]
Documentation changed. Please, check if it's ok.

**Comment by m1ci** [comment]
> roundtripping only works when the input format is equal to the output format.

Why not allowing input: HTML, output: NIF?... yes this is not round-tripping but, I can then use the NIF, do smth with it, and convert it back to HTML. For such scenarios, input and output format should not be the same.

It can be good to highlight (put in bold) the part saying: "This is a general rule when performing the round-tripping: input and output formats must be the same". Otherwise, the documentation looks much better.

**Comment by m1ci** [comment]
Also, I dont think the statement "roundtripping only works when the input format is equal to the output format" is true. To me it worked HTML to Turtle. See the example in https://github.com/freme-project/e-Internationalization/issues/18

**Comment by borriellom** [comment]
Yes, it works from HTML to Turtle, but it's not round-tripping.
In this scenario you are simply invoking a FREME e-Service over a HTML file. The result is turtle as usual. Its explained in the first part of documentation, where I talk about the conversion to NIF.

The actual round-tripping is performed only if input and output formats are the same. That doesn't mean that e-Internationalization returns an error if you specify HTML as input format and Turtle as output format. It simply means that if you want perform the round-tripping you have to provide same input and output formats.

**Comment by m1ci** [comment]
ok ,thanks for clarification
