### ISSUE TITLE
[test] improve documentation for e-Internationalization

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#16]
The documentation at http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html is not sufficient.

Already in the beginning is should be clear what e-Internationalization does and how. Some points to cover
- it is not an individual service, but it is indirectly used via the other services
- already in the beginning include example and explicitly explain that this is not stand alone service
- the "Conversion to NIF" is misleading. Maybe reformulate it like: 1) entity recognition with over HTML, 2) enrichment of HTML with e-Link, 3) translation of HTML, 4) term extraction in HTML
- move the "how it works" section from the end of the page to the very beginning. also round-tripping should be explained at the beginning.
- provide example for round-tripping. Yes there are some, but entitle those examples as round-tripping and explain what it is and again, some example
- explicitly state which services are supported with e-Internationalization
- explicitly state what input and output formats are support. Note that this differ for each service. So explain how the formats are handled for each service
- summarize what ITS properties are supported, I found out the "confidence" property is not supported

**Comment by jnehring** [comment]
I agree with these points.

**Comment by borriellom** [comment]
New version of e-Internationalization just committed. Please, let me know if it's clearer now and feel free to correct my English!

**Comment by m1ci** [comment]
thanks Marta, some comments:

> it is not an individual service, but it is indirectly used via the other services

thanks for adding this info. To avoid confusion I suggest removing the word "service" from the 2nd sentence "The e-Internationalization service let users..."

> already in the beginning include example and explicitly explain that this is not stand alone service

OK.

> the "Conversion to NIF" is misleading. Maybe reformulate it like: 1) entity recognition with over HTML, 2) enrichment of HTML with e-Link, 3) translation of HTML, 4) term extraction in HTML

> move the "how it works" section from the end of the page to the very beginning. also round-tripping should be explained at the beginning.

This seems its not done. Since the service is all about round-tripping I suggest moving "Round-tripping: how does it work?" between the first examples.

> provide example for round-tripping. Yes there are some, but entitle those examples as round-tripping and explain what it is and again, some example

OK.

> explicitly state which services are supported with e-Internationalization

OK.

> explicitly state what input and output formats are support. Note that this differ for each service. So explain how the formats are handled for each service

OK.

> summarize what ITS properties are supported, I found out the "confidence" property is not supported

There is info on what is NOT support, but there is no info on what IS supported.

**Comment by borriellom** [comment]
Done. I think I didn't miss any point this time.

**Comment by m1ci** [comment]
thanks, looks great!
