### ISSUE TITLE
[test] unclear behaviour of the translate property

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#19]
if the property "translate" is not set, then the whole text is being translated?

**Comment by borriellom** [comment]
Where did you read about that property? Is it the ITS translate? That ITS category is not supported by e-Internationalization.

**Comment by m1ci** [comment]
Yes, its part of ITS translate. This is related to https://github.com/freme-project/e-Internationalization/issues/18

Closing the issue because ITS translate data category is still not supported.
