### ISSUE TITLE
[test] typo in the e-Internationalization description 

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#20]
In http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html
there is following typo:
```
Original file
![Image of ODT file]
(https://github.com/freme-project/Documentation/blob/master/img/odtFile.png)
```

**Comment by borriellom** [comment]
That's not a typo. It's the reference to an image. I don't why it's not properly displayed when the md file is converted to HTML.

**Comment by jnehring** [comment]
@josauder can you please check whats wrong here?

**Comment by josauder** [comment]
The mistake was that https://github.com/freme-project/Documentation/blob/master/img/odtFile.png is not an image file, but a GitHub page which contains the image. I fixed it with the latest commit.
