### ISSUE TITLE
[test] use of proper terminology: ITS properties and not ITS tags

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#21]
This can be read in the section "Note on ITS tags" in http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html

**Comment by borriellom** [comment]
I'm not so sure what to do. Shall I simply replace the word "tags" with the word "properties" in the documentation?

**Comment by m1ci** [comment]
yes, please. This is just a suggestion

**Comment by borriellom** [comment]
Ok, I'll do it.

**Comment by borriellom** [comment]
Done.

**Comment by borriellom** [comment]
Please check if it's ok.

**Comment by m1ci** [comment]
OK. Well done.
