### ISSUE TITLE
Segmentation issue for HTML roundtripping

### ISSUE THREAD

**Issue by fsasaki** [freme-project/e-Internationalization#28]
[request4.txt](https://github.com/freme-project/e-Internationalization/files/25920/request4.txt)
[out4.txt](https://github.com/freme-project/e-Internationalization/files/25919/out4.txt)
[html-in.txt](https://github.com/freme-project/e-Internationalization/files/25918/html-in.txt)
The attached request with the attached html input leads to segementation issues. E.g. "Yves Desmet" is correctly recognized, but the output dublicates the last character "t":
&lt;span
                its-ta-ident-ref="http://nl.dbpedia.org/resource/Yves_Desmet"
                its-ta-class-ref="http://nerd.eurecom.fr/ontology#Person"
                its-ta-confidence="0.9869452659937508">Yves Desmet&lt;/span>t
This seems to be a regular error, see the output for details.

**Comment by borriellom** [comment]
Fixed. Please, check if it works now.

**Comment by fsasaki** [comment]
works, thanks!
