### ISSUE TITLE
Tutorial example for e-Internationalization and e-Link does not work

### ISSUE THREAD

**Issue by fsasaki** [freme-project/e-Internationalization#29]
I tried the example at 
http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html
"This example shows how to invoke the e-Link service over a HMTL file. ... HTML file containing an entity"
I get back the attached TTL file, which contains no e-Link information.
[temp-enrichment.txt](https://github.com/freme-project/e-Internationalization/files/27807/temp-enrichment.txt)
Not sure if this is a bug of e-internationalization or an issue with e-Link?

**Comment by borriellom** [comment]
Fortunately it's not a bug. The request used in the documentation refers to the last deployed version, that is FREME 0.3 at the moment. That request will work when FREME 0.4 is deployed.
At the moment you can try with the current development version, by using the cURL request below 

```
curl -X POST -d @docTestWithEntity.html --header "Content-Type: text/html" "http://api-dev.freme-project.eu/current/e-link/documents/?outformat=turtle&templateid=3"
```

**Comment by fsasaki** [comment]
Ah, you are right - sorry for the confusion, works fine with the development version.
