### ISSUE TITLE
e-Internationalization adds unnecessary tags

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#31]
Moved from https://github.com/freme-project/technical-discussion/issues/92 to this repo.

The HTML5 roundtripping changes html content in some cases. 

e.g. this curl request
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.4/e-entity/freme-ner/documents?input=%3Cp%3Ehello%20world%3C%2Fp%3E&informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all"
`

has this HTML as input

```
<p>hello world</p>
```

and produces this HTML as output:

```
<!DOCTYPE html>
<html><head><body><p>hello world</p></body></html>
```

I think this causes problems in some use cases. E.g. when you want to enrich a snippet of a HTML page and replace the original snippet with the enriched snipped.

**Comment by borriellom** [comment]
We should try to find a workaround. I think that this is the way Okapi works, because it is meant to work on complete documents and not on snippets. 
The alternative option would be writing new code acting similar to Okapi and capable to manage snippets of documents.

**Comment by ysavourel** [comment]
We could probably have an option in Okapi to not generate the missing code.
I'll try to look at it this week-end.

**Comment by ysavourel** [comment]
I've looked at the HTML5 code quickly and I see where we add the `<!DOCTYPE html>` part, but not the `<html>`, etc. parts.
That may come from the underlying HTML5 library (nu.validator.htmlparser).

**Comment by fsasaki** [comment]
@sideshowbarker said: the validator.nu html parser will parse the source into an event stream that includes the head/body and </p> end tags, etc.. The parser if used by itself with its DOM API will always construct a DOM that includes the head/body and </p> end tags, etc. Any conforming HTML parser will do that always. It is required by the HTML spec. For the workflow discussed in this issue there is no clear solution. A workaround is to create an abstraction that kind of fakes the full document.

**Comment by jnehring** [comment]
How about a "hacky" solution? After e-Internationalization has created the HTML document and added the unwanted tags, we could use this algorithm:
- Check if the output document starts and ends with the tag we do not want
- Check if the original document starts and ends with these tags
- If the first check if true and the second check is false then e-Internationalization removes the unwanted tags from the output HTML and sends a clean document back to the client.

**Comment by jnehring** [comment]
@fsasaki  proposed my algorithm with a modification which is more robust then my suggestion:

When e-internationalization gets this input:

<p>hello world</p>

Then it checks if the input does start with <!DOCTYPE html> and &lt;html>. If yes it does not do anything. Else it wraps the data with a div element like this:

```
<div class="freme-e-internationalization">
  <p>hello world< p>
</div>
```

Then it performs the enrichment. When the output HTML is created then e-Internationalization scans the DOM for the div with this class. Then it returns only the HTML that is contained inside of the div.

**Comment by jnehring** [comment]
@katia-vistatec fixed the problem. In broker-local package it works fine but in broker-dev there is still an error:

input `<p>hello world</p>` gets converted correctly to output `<p>hello world</p>`
input 

```
<!DOCTYPE html>
<p>hello world</p>
```

get converted to 

```
<p>hello world</p>
```

So the DOCTYPE gets stripped.

I think it is some kind of version problem. I will take over from here.

**Comment by jnehring** [comment]
I wanted to test this but I could not test because of https://github.com/freme-project/e-Internationalization/issues/40

**Comment by jnehring** [comment]
The problem that hinders solving this issues was moved to https://github.com/freme-project/e-Internationalization/issues/35

**Comment by jnehring** [comment]
This works now.
