### ISSUE TITLE
Failing e-Internationalization unit test

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#34]
One of the brokers unit test fails:

http://rv1443.1blu.de:8082/job/Broker/672/ says
```
Failed tests: 
  EInternationalizationTest.testOdt:151 expected:<400> but was:<200>

Tests run: 42, Failures: 1, Errors: 0, Skipped: 0

[ERROR] There are test failures.
```

@borriellom can you please check whats wrong there and maybe fix the problem?

**Comment by borriellom** [comment]
That's a test from the Broker unit tests. I don't know why the response was 400. Nothing has changed in the management of odt files in e-Internationalization.

**Comment by jnehring** [comment]
Sorry for the noise. I think the test failed because of https://github.com/freme-project/freme-ner/issues/64 . So the problem originates from FREME NER and not from e-Internationalization.

I leave this open. We will check again if the tests fail when the issue with FREME NER is solved.

**Comment by jnehring** [comment]
FREME NER is up and running but the problem still occurs.

@ArneBinder  can you please try to fix the problem?

**Comment by jnehring** [comment]
The problem originates from within e-Internationalization. I added some debug output to the [ODT unit test](https://github.com/freme-project/e-Internationalization/blob/master/src/test/java/eu/freme/i18n/okapi/api/EInternationalizationAPITest.java#L135). A test ODT file with some content gets converted to

```
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix dc:    <http://purl.org/dc/elements/1.1/> .

<http://freme-project.eu/~okapi-23_OpenOfficeFilter_1850160987989945710.tmp/#char=0,0>
        a       nif:String , nif:Context , nif:RFC5147String .
```

There is no isString property. This causes the failure.

**Comment by borriellom** [comment]
This should be fixed now. Please, @jnehring  check if tests are successful now.

**Comment by jnehring** [comment]
Works fine. Thank you
