### ISSUE TITLE
String Index out of bounds exception

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#35]
This issue was reported by @pheyvaer and moved from https://github.com/freme-project/freme-ner/issues/78

The same call as in issue #76, however this time we ask to output the result using text/html. However, we get the following error
```
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Feb 17 16:02:27 CET 2016</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>String index out of range: -14</div></body></html>
```
What exactly is the problem here?

P.S. According to the w3 validator our document is valid (beside some deprecated elements, however, that should not make a difference I think).

**Comment by borriellom** [comment]
Thanks for reporting this.
Never seen this behavior so far. I'll have a look as soon as possible.

**Comment by fsasaki** [comment]
I processed the file attached to https://github.com/freme-project/freme-ner/issues/76
https://github.com/freme-project/freme-ner/files/133952/SB50.zip
and processed it with 
1) e-entity and output turtle: works as exected
2) e-entity and output html: gives he error reported here with this error message

>  {"timestamp":1455733543376,"status":500,"error":"Internal Server Error","exception":"java.lang.StringIndexOutOfBoundsException","message":"String index out of range: -14","path":"/e-entity/freme-ner/documents"}

3) e-Terminology and output turtle or html: both work as expected - html as well.
[output-e-terminology-as-html-issue-35.txt](https://github.com/freme-project/e-Internationalization/files/134918/output-e-terminology-as-html-issue-35.txt)

Not sure if this helps, but 3) shows that this works with other e-services, so maybe the issue is on how things come back from freme-ner to e-internationalisation.

**Comment by jnehring** [comment]
I tested it and I can reproduce the bug. I also checked the log files on FREME dev. They say

```
ERROR   2016-02-17 19:25:43,374 [http-nio-8084-exec-5] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]  - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -14
        at java.lang.String.substring(String.java:1967)
        at eu.freme.i18n.okapi.nif.converter.HTMLBackConverter.convertBack(HTMLBackConverter.java:127)
        at eu.freme.i18n.okapi.nif.converter.HTMLBackConverter.convertBack(HTMLBackConverter.java:105)
        at eu.freme.i18n.okapi.nif.converter.HTMLBackConverter.convertBack(HTMLBackConverter.java:75)
        at eu.freme.i18n.api.EInternationalizationAPI.convertBack(EInternationalizationAPI.java:81)
        at eu.freme.broker.tools.internationalization.ConversionHttpServletResponseWrapper.writeBackToClient(ConversionHttpServletResponseWrapper.java:61)
        at eu.freme.broker.tools.internationalization.EInternationalizationFilter.doFilter(EInternationalizationFilter.java:299)
```
So we can see that the bug originates from within e-Internationalization.

**Comment by fsasaki** [comment]
Thanks, Jan. It's still unclear to me why this works with other HTML documents and e-Entity roundtripping, and why it works with e-Terminology and the same HTML document.

**Comment by jnehring** [comment]
The same problem occurs here: http://rv2622.1blu.de:7001/e-entity/freme-ner/documents?language=en&dataset=dbpedia&input=%3Cp%3EWelcome%20to%20Berlin!%3C%2Fp%3E&informat=text/html&outformat=text/html

**Comment by Katsivelisp** [comment]
Hi,

I don't know if this is really related, but I get the same error when running [this call](http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=gwpp-glossary&mode=all&input=%3Cp%3EPolyomaviruses%20have%20been%20described%20as%20to%20be%20highly%20stable%20viruses.%20Polyomaviruses%20appear%20to%20be%20relatively%20resistant%20to%20UUVCirradiation.%20%26nbsp%3BThe%20viruses%20are%20also%20stable%20over%20a%20wide%20range%20of%20pH%20found%20in%20natural%20waters.%20In%20evaluating%20the%20stability%20of%20polyomaviruses%20in%20sewage%20at%2020%C2%BAC%2C%20BBofill-Masand%20coworkers%20estimated%26nbsp%3B%3Ca%3Ea%20T%3Csub%3E90%3C%2Fsub%3E%3C%2Fa%3E%26nbsp%3Bof%2026.7%20days%26nbsp%3Band%20a%20T%3Csub%3E99%26nbsp%3B%3C%2Fsub%3Eof%2061.5%20days%20for%20JCPyV.%3C/p%3E).

The context being that I'm using the CKEditor Plugin to perform linking against a custom dataset.

**Comment by jnehring** [comment]
This problem is fixed.
