### ISSUE TITLE
String index out of bounds exception

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#40]
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&input=%3Cp%3EWelcome%20to%20Berlin!%3C%2Fp&informat=text/html&outformat=text/html

sends this text to FREME NER:

```
<p>Welcome to Berlin!</p
```

and it produces

```
<html>
    <body>
        <h1>Whitelabel Error Page</h1>
        <p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p>
        <div id='created'>Wed Jun 15 15:05:50 CEST 2016</div>
        <div>There was an unexpected error (type=Internal Server Error, status=500).</div>
        <div>String index out of range: -18</div>
    </body>
</html>
```

@katia-vistatec this bug sounds familiar to me but I cannot find the related GitHub issue. Did you already fix this?

**Comment by katia-vistatec** [comment]
It seems to me the same bug #35 caused by e-tilde failure.

**Comment by jnehring** [comment]
I think it is not related to #35. I did further testing and it fails only when the input is send via the query string, it works when the input is send via request body. So I assume the problem is within e-Internationalization filter.

**Comment by katia-vistatec** [comment]
Hi Jan. I mean that also for issue #35 there was the same problem when speifying informat and outformat as text/html.

**Comment by jnehring** [comment]
@katia-vistatec you are right. this is a dublicate of #35
