### ISSUE TITLE
migrate FREME to higher version than 0.6

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#41]
@katia-vistatec claims that FREME dev is using e-Internationalization  version 0.6. @jnehring Can we migrate to a higher version? Reason: provenance is not handled in 0.6.

**Comment by m1ci** [comment]
for more, see the conversation https://github.com/freme-project/e-Internationalization/issues/32#issuecomment-256969385

**Comment by fsasaki** [comment]
Hi Milan, sorry for jumping in, Jan may need one or two weeks to come back to this, being busy with other stuff. If this is missing critical we may need a different way to move forward ...

**Comment by m1ci** [comment]
Thanks for the message, Felix! Actually, I needed this for the D1.7.
@sandroacoelho do you think you can configure FREME DEV to use higher version than 0.6? Maybe you try first on localhost if that will work.

**Comment by jnehring** [comment]
I updated e-Internationalization on freme-dev to the latest version 0.8-SNAPSHOT. Please test

**Comment by m1ci** [comment]
this works now, thanks
