### ISSUE TITLE
entities not annotated in HTML

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#42]
if I process

```
<html>
 <head> 
  <title></title> 
 </head> 
 <body> 
  <p>Welcome to Europe.</p> 
 </body>
</html>
```

I get 
```
<html its-ta-annotators-ref="http://freme-project.eu/tools/freme-ner">
 <head> 
  <title></title> 
 </head> 
 <body> 
  <p>Welcome to Europe.</p> 
 </body>
</html>
```

but the entities are  not annotated (in <span> element).
try:
curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d @data.html "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all&nif-version=2.1"

**Comment by jnehring** [comment]
@borriellom checks back with @philinthecloud when this can be fixed.

**Comment by borriellom** [comment]
We should be able to fix it in two weeks.

**Comment by katia-vistatec** [comment]
Ok. I'm working on it. I think I understood the problem for nif 2.1 and I corrected (not yet pushed to repository) but I noticed a weird output in the case of nif 2.0 both for outformat text/turtle and text/html, when making the call pointing to freme-dev. See attached files:
[resulthtml.txt](https://github.com/freme-project/e-Internationalization/files/581477/resulthtml.txt)
[resulttl.txt](https://github.com/freme-project/e-Internationalization/files/581478/resulttl.txt)
[calls.txt](https://github.com/freme-project/e-Internationalization/files/581480/calls.txt)

**Comment by katia-vistatec** [comment]
For nif 2.1 the enriched nif is attached and it has different information:
[enriched.txt](https://github.com/freme-project/e-Internationalization/files/581488/enriched.txt)
It seemed to me that the call using nif 2.0 it was working a few hours ago.
Can you test the outputs for nif 2.0?

**Comment by m1ci** [comment]
> I noticed a weird output in the case of nif 2.0 both for outformat text/turtle and text/html

what is not OK there?

The enriched.txt file you attached is NIF. I am asking for "in:HTML, out:HTML"

**Comment by katia-vistatec** [comment]
Milan could you try the call with nif 2.0 with output html and output nif?

**Comment by katia-vistatec** [comment]
If you run the calls in calls.txt (that are for nif 2.0) you got an html without enrichments and a nif which does not consider Berlin and Welcome as entities. I have just noticed now that the same is happening with nif 2.1.

**Comment by katia-vistatec** [comment]
[yesterday-nif-21.txt](https://github.com/freme-project/e-Internationalization/files/583028/yesterday-nif-21.txt)
[today-nif-21.txt](https://github.com/freme-project/e-Internationalization/files/583029/today-nif-21.txt)

**Comment by katia-vistatec** [comment]
Above are attached the nif 2.1 files of yesterday and today. For my changes I based on the yesterday-nif-21 which is different from the today-nif-21. This last one doesn't have"Berlin" and "Welcome" as entities.
The same is happening for nif 2.0.

**Comment by m1ci** [comment]
works, thanks @katia-vistatec @borriellom
