### ISSUE TITLE
API for roundtripping

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#7]
* provide additional method in EInternationalizationAPI which takes enrichment+original file and provides the final output file as stream.
* provide additional method in EInternationalizationAPI which produces the NIF containing original markup.

**Comment by jnehring** [comment]
I tried to make this work but I did not succeed. @borriellom  can you please add a unit test to the EInternationalizationAPITest.java that shows how to use the code to do the roundtripping?

I added some sample data for the unit test in a branch. The commit is attached to the issue. You can use this or you create a new one.

**Comment by borriellom** [comment]
I changed the unit test "testRoundtripping" in the "EInternationalizationAPITest" class. It is committed in the unittest branch.

The workflow is described below.

1. Submit the original html file to the convertToTurtleWithMarkups method. It creates the skeleton file: the turtle file with the context including markups.
2. Save the skeleton file somewhere on the machine.
3. Submit the original html file to the convertToTurtle method. It creates the enriched file (this step is not included in the test, I used the sample enriched file you provided in the roundtripping folder)
4. Submit the skeleton file and the enriched file to the convertBack method. It creates the original file enriched with annotation from FREME.

While running the test I noticed that Okapi adds \<html\>, \<head\> and \<body\> tag even if the original document doesn't contain them. The \<head\> tag is not closed in the document generated by the roundtripping. I checked and I found out the Okapi adds this tag without closing it. 
Moreover, the taConfidence property is not included in the final document. Is that property inserted by FREME? If yes, I should manage that property as soon as I have time.

**Comment by jnehring** [comment]
Thanks this was helpful

**Comment by ysavourel** [comment]
> While running the test I noticed that Okapi adds <html>, <head> and
> <body> tag even if the original document doesn't contain them. The 
> <head> tag is not closed in the document generated by the roundtripping.

Just an explanation: I think we do that to add the encoding declaration (so the translated file get the right encoding).

> I checked and I found out the Okapi adds this tag without closing it. 

We probably should close it properly.
On the other hand, if <head> was added, it means the initial file wasn't quite valid already.

**Comment by jnehring** [comment]
Yes true. I created #7 to discuss this.
