### ISSUE TITLE
Roundtripping for long html

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Internationalization#9]
I was playing around with e-Internationalization on normal data. I took the html source of http://vistatec.ie and send it to FREME NER. When I use `informat=text/html` and `outformat=turtle` (conversion from html to NIF) then the call is very fast. But when I use `informat=text/html` and `outformat=text/html` (html roundtripping) then the api call gets a timeout after 30 seconds.

In the branch "long-roundtripping" I created a [unit test for long roundtripping](https://github.com/freme-project/e-Internationalization/blob/long-roundtripping/src/test/java/eu/freme/i18n/okapi/api/EInternationalizationAPITest.java#L232). It performs above mentioned conversion from NIF to HTML. I started it and it did not respond for 10 minutes.

For small html pages like `<p>Welcome to Berlin</p>` the roundtripping works but for a normal real world HTML it seems to be too slow.

**Comment by borriellom** [comment]
It's not too slow. There was a bug and with this html it executed an infinite loop at some point.
I also fixed other small issues. Changes have been committed in the master branch.
While fixing the bug I found out a new issue: #11

**Comment by jnehring** [comment]
I tested it and now it works fine and fast. Thank you!
